/** Marcas efetivamente vistas nas publicações da loja. */
export const brands = [
  "Lubrax",
  "Petronas Tutela",
  "Texaco",
  "Ipiranga",
  "Bardahl",
  "Militec-1",
  "Paraflu",
  "Radnaq",
  "MSX",
  "Kondor",
  "Haizer",
  "Abro",
  "Proauto",
  "Grand Prix",
  "Orbi Química",
  "Little Trees",
  "Luxcar",
  "WD-40",
  "Gitanes",
  "Indisa",
  "Tek Bond",
  "Cinoy",
  "Hulk",
  "SW",
  "Cariocar",
  "Car 80",
  "Chesy Lub",
];
