/** Marcas efetivamente vistas nas publicações da loja. */
export const brands = [
  "Lubrax",
  "Petronas",
  "Texaco",
  "Ipiranga",
  "Bardahl",
  "Militec-1",
  "Paraflu",
  "Radnaq",
  "MSX",
  "Kondor",
  "Haizer",
  "Abro",
  "Grand Prix",
  "Orbi Química",
  "Little Trees",
  "WD-40",
  "Gitanes",
  "Indisa",
  "Proauto",
  "Cindy",
  "Hulk",
  "Cariocar",
];
